os:
 - linux

dist: focal

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - wget
      - openssl

before_install:
  - pwd
  - ls -al
  - ls -al .ssh/
  - openssl aes-256-cbc -K $encrypted_af65e16f4620_key -iv $encrypted_af65e16f4620_iv -in id_rsa.vcity_rict.enc -out id_rsa.vcity_rict -d
  - ls -al .ssh
  - ls -al
  - wc id_rsa.vcity_rict

before_script:
  # Requiring a [d|r]ecent version of Hugo
  # References:
  #  - For the Travis phase within the job lifecycle
  #    https://docs.travis-ci.com/user/installing-dependencies/
  #  - For the Hugo install process
  #    https://www.howtoforge.com/how-to-install-hugo-site-generator-on-ubuntu/
  #- wget https://github.com/gohugoio/hugo/releases/download/v0.58.2/hugo_0.58.2_Linux-64bit.deb
  #- sudo dpkg -i hugo_0.58.2_Linux-64bit.deb
  - wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.deb
  - sudo dpkg -i hugo_0.74.3_Linux-64bit.deb
  - hugo version

script:
  - cd Website
  - hugo
  - which bash

deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/.travis.deploy.sh
    skip_cleanup: true
    on:
      branch: master
