# We use the toml format for the configuration because placing comments
# in yaml is not easy (not to mention it's possible hugo side-effects).
# section is not taken into account when defined in the yaml config file...

baseURL = "."
#languageCode = "en-us"
#title = "DatAgora"

# For images to be found in content/
#canonifyURLs = "true"
#relativeURLs = "true"
uglyURLs = "true"
#disablePathToLower = "true"
theme = "hyde"

# see https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
# and https://gohugo.io/getting-started/configuration-markup
[markup.goldmark.renderer]
unsafe = true

DefaultContentLanguage = "en"

sectionPagesMenu = "main"
[Languages]
  [Languages.en]
    title = "DatAgora EN"
    languageName = "English"
    #languageCode = "en-us"
    weight = 1

  [Languages.fr]
    title = "DatAgora FR"
    languageName = "Français"
    #languageCode = "fr-fr"
    contentDir = "content/fr"
    weight = 2

# The following navigation lists are used in the sidebar template (see themes/hyde/layouts/partials/sidebar.html).
[Menus]
  main = [
    { Name = "Home", URL = "/", weight=1},
#
    { Name = "Principles", URL = "principles", weight=20},
    { Name = "Projects", URL = "projects", weight=21},
    { Name = "Components", URL = "components", weight=22},
#
    { Name = "Team", URL = "team", weight=30},
    { Name = "Partners", URL = "partners", weight=31},
#
    { Name = "Publications", URL = "Publications", weight=40},
    { Name = "Events", URL = "events", weight=41},
  ]
  mainfr = [
#todo ?
#    { Name = "Principes", URL = "Principles", weight=1},
#    { Name = "Methodologie",    URL = "Our-methodology", weight=2},
#    { Name = "Données & XP", URL = "Donnees-et-Experimentations", weight=3},
#    { Name = "Données & Composants", URL = "Components", weight=4},
#    { Name = "Données & Agora", URL = "Agora", weight=5},
#    { Name = "Champs d'étude", URL = "Field-of-studies", weight=6},
#    { Name = "Qui sommes nous?", URL = "About", weight=7},
#    { Name = "Partenaires", URL = "Partners", weight=8},
#    { Name = "Contact", URL = "Contact", weight=9},
#    { Name = "Postes à pourvoir", URL = "Positions", weight=10},
  ]

# Notes: it seems that the now default markdown handler (goldmark) can NOT be
# configured to avoid the rendering of a plain ASCII single quote (in the
# Markdown source file) as a "&rsquo;" in the genereted website. Refer to
# https://iwalt.com/blog/2019/12/hugo-goldmark-and-smartypants/
