# We use the toml format for the configuration because placing comments
# in yaml is not easy (not to mention it's possible hugo side-effects).
# section is not taken into account when defined in the yaml config file...

baseURL = "."
#languageCode = "en-us"
#title = "DatAgora"

# For images to be found in content/
#canonifyURLs = true
#relativeURLs = "true"
uglyURLs = "true"
#disablePathToLower = "true"
theme = "hyde"

# see https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
# and https://gohugo.io/getting-started/configuration-markup
[markup.goldmark.renderer]
unsafe = true

DefaultContentLanguage = "en"

sectionPagesMenu = "main"
[Languages]
  [Languages.en]
    title = "DatAgora EN"
    languageName = "English"
    #languageCode = "en-us"
    weight = 1
  [Languages.fr]
    title = "DatAgora FR"
    languageName = "Français"
    #languageCode = "fr-fr"
    contentDir = "content/fr"
    weight = 2

[Menus]
  main = [
    { Name = "Principles", URL = "Principles", weight=1},
    { Name = "Methodology",    URL = "Our-methodology", weight=2},
    { Name = "Data & XP", URL = "Données-et-Expérimentations", weight=3},
    { Name = "Data & Components", URL = "Components", weight=4},
    { Name = "Data & Agora", URL = "Agora", weight=5},

    { Identifier = "fos", Name = "Field of studies", URL = "Field-of-studies", weight=10},
    #{ Parent = "fos", Name = "Game, mediation and public space", URL = "Game-mediation-and-public-space", weight=1},
    #{ Parent = "fos", Name = "Analysis of urban mobility flows", URL = "Analysis-of-urban-mobility-flows", weight=2},
    #{ Parent = "fos", Name = "Search in a documentary corpora", URL = "Search-in-documentary-corpora", weight=3},
    #{ Parent = "fos", Name = "Observations of the exchanges", URL = "Observations-of-the-exchanges", weight=4},
    
    { Name = "About us", URL = "About", weight=20},
    { Name = "Partners", URL = "Partners", weight=21},
    { Name = "Contact", URL = "Contact", weight=22},
    { Name = "Open positions", URL = "Positions", weight=23},

    #{ Name = "Geonum 2020", Identifier = "geonum_20", URL = "fr/geonum_20/Projet_Geonum_20", weight=1000},
    #{ Name = "Végétaliser urbain", Identifier = "geonum_20_vegurban", Parent = "geonum_20", URL = "fr/geonum_20/Végétaliser_urbain", weight=1}
  ]



# Notes: it seems that the now default markdown handler (goldmark) can NOT be
# configured to avoid the rendering of a plain ASCII single quote (in the
# Markdown source file) as a "&rsquo;" in the genereted website. Refer to
# https://iwalt.com/blog/2019/12/hugo-goldmark-and-smartypants/
