# We use the toml format for the configuration because placing comments
# in yaml is not easy (not to mention it's possible hugo side-effects).
# section is not taken into account when defined in the yaml config file...

baseURL = "."
#languageCode = "en-us"
#title = "DatAgora"

# For images to be found in content/
canonifyURLs = true
#relativeURLs = "true"
#uglyURLs = "true"
theme = "hyde"

# see https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
# and https://gohugo.io/getting-started/configuration-markup
#[markup.goldmark.renderer]
#unsafe = true

DefaultContentLanguage = "en"

sectionPagesMenu = "main"
[Languages]
  [Languages.en]
    title = "DatAgora EN"
    languageName = "English"
    #languageCode = "en-us"
    weight = 1
  [Languages.fr]
    title = "DatAgora FR"
    languageName = "Français"
    #languageCode = "fr-fr"
    weight = 2

[Menus]
  main = [
    { Name = "Principles", URL = "principles", weight=1},
    { Name = "About us", URL = "about", weight=97},
    { Name = "Partners", URL = "partners", weight=98},
    { Name = "Contact", URL = "contact", weight=99},
    { Name = "Open positions", URL = "positions", weight=100},

    { Identifier = "proposals", Name = "Our proposals", URL = "proposals", weight=101},
    { Parent = "proposals", Name = "Our projects", URL = "proposals/projects", weight=1},
    { Parent = "proposals", Name = "Proposed stations", URL = "proposals/stations", weight=2},
    { Parent = "proposals", Name = "Our methodology",    URL = "proposals/methodology", weight=3},

    { Name = "Geonum 2020", Identifier = "geonum_20", URL = "fr/geonum_20", weight = 1000},
    { Name = "Végétaliser urbain", Identifier = "geonum_20_vegurban", Parent = "geonum_20", URL = "fr/geonum_20/vegetaliser_urbain", weight = 1001}
  ]
  # The 80 columns coding style cannot be enforced otherwise hugo
  # triggers a "newlines not allowed within inline tables" error
  fieldofstudies = [
    { Name = "Game, mediation and public space", URL = "/fieldofstudies/gmps", weight=2},
    { Name = "Analysis of urban mobility flows", URL = "/fieldofstudies/analysisofurbanmobilityflows", weight=3},
    { Name = "Search in a documentary corpora", URL = "/fieldofstudies/searchindocumentarycorpora", weight=4},
    { Name = "Representation of physical phénomenon", URL = "/fieldofstudies/representationofphysicalphenomenon", weight=5},
    { Name = "Observations of the exchanges",    URL = "/fieldofstudies/observationsoftheexchanges", weight=6}
  ]




# Notes: it seems that the now default markdown handler (goldmark) can NOT be
# configured to avoid the rendering of a plain ASCII single quote (in the
# Markdown source file) as a "&rsquo;" in the genereted website. Refer to
# https://iwalt.com/blog/2019/12/hugo-goldmark-and-smartypants/
